#!/usr/bin/env python3
"""
setup_workspace.py — Auto-generates workspace.json for android-emulator-qa skill.

Detects Android SDK tools (adb, emulator) and available AVDs.
Does NOT scan or record project info — the AI resolves the current project
from the active workspace context.

Usage:
  python3 setup_workspace.py --skill-dir ~/.gemini/antigravity/skills/android-emulator-qa
  python3 setup_workspace.py --skill-dir .agents/skills/android-emulator-qa
  python3 setup_workspace.py --skill-dir /path/to/skill --dry-run
"""

import argparse
import json
import os
import platform
import shutil
import subprocess
from pathlib import Path


def find_android_sdk() -> Path | None:
    """Detect Android SDK root across Linux, macOS, and Windows."""
    for var in ["ANDROID_HOME", "ANDROID_SDK_ROOT"]:
        val = os.environ.get(var)
        if val and Path(val).exists():
            return Path(val)

    home = Path.home()
    system = platform.system()

    candidates: list[Path] = []
    if system == "Linux":
        candidates = [home / "Android" / "Sdk"]
    elif system == "Darwin":
        candidates = [home / "Library" / "Android" / "sdk"]
    elif system == "Windows":
        local_app = os.environ.get("LOCALAPPDATA", "")
        candidates = [
            Path(local_app) / "Android" / "Sdk",
            home / "AppData" / "Local" / "Android" / "Sdk",
        ]

    for path in candidates:
        if path.exists():
            return path
    return None


def find_tool(name: str, sdk: Path | None, subpath: str) -> str | None:
    """Find a tool on PATH first, then fall back to known SDK location."""
    found = shutil.which(name)
    if found:
        return found
    if sdk:
        exe_suffix = ".exe" if platform.system() == "Windows" else ""
        candidate = sdk / (subpath + exe_suffix)
        if candidate.exists():
            return str(candidate)
    return None


def find_python() -> str:
    for name in ["python3", "python"]:
        found = shutil.which(name)
        if found:
            try:
                result = subprocess.run(
                    [found, "--version"], capture_output=True, text=True, timeout=5
                )
                output = result.stdout + result.stderr
                if "Python 3" in output:
                    return found
            except Exception:
                pass
    return "python3"


def list_avds(emulator_path: str | None) -> list[str]:
    tool = emulator_path or shutil.which("emulator")
    if not tool:
        return []
    try:
        result = subprocess.run(
            [tool, "-list-avds"], capture_output=True, text=True, timeout=10
        )
        return [line.strip() for line in result.stdout.splitlines() if line.strip()]
    except Exception:
        return []


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Auto-generate workspace.json for android-emulator-qa skill."
    )
    parser.add_argument(
        "--skill-dir",
        required=True,
        help="Path to the skill directory where workspace.json will be written.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated config without writing it.",
    )
    args = parser.parse_args()

    print("🔍 Detecting Android SDK...", flush=True)
    sdk = find_android_sdk()
    adb = find_tool("adb", sdk, "platform-tools/adb")
    emulator = find_tool("emulator", sdk, "emulator/emulator")
    python = find_python()

    if sdk:
        print(f"   ✅ SDK: {sdk}")
    else:
        print("   ⚠️  Android SDK not found. Set ANDROID_HOME or install Android Studio.")

    if adb:
        print(f"   ✅ adb: {adb}")
    else:
        print("   ⚠️  adb not found.")

    if emulator:
        print(f"   ✅ emulator: {emulator}")

    print("🔍 Listing AVDs...", flush=True)
    avds = list_avds(emulator)
    if avds:
        print(f"   ✅ AVDs: {', '.join(avds)}")
    else:
        print("   ⚠️  No AVDs found. Create one in Android Studio.")

    config = {
        "_comment": (
            "Machine-specific config for android-emulator-qa skill. "
            "Auto-generated by setup_workspace.py — do not commit. "
            "Projects are NOT listed here; the AI resolves them from the active workspace."
        ),
        "sdk": {
            "root": str(sdk) if sdk else "",
            "adb": adb or "",
            "emulator": emulator or "",
            "python": python,
        },
        "avds": avds,
    }

    if args.dry_run:
        print("\n📋 Generated workspace.json (dry run):")
        print(json.dumps(config, indent=2))
        return 0

    skill_dir = Path(args.skill_dir).expanduser().resolve()
    skill_dir.mkdir(parents=True, exist_ok=True)
    output_path = skill_dir / "workspace.json"
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
        f.write("\n")

    print(f"\n✅ workspace.json written to: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
